### ISSUE TITLE
.tiff files are black

### ISSUE THREAD

**Issue by johnmathews** [julimueller/dtld_parsing#10]
Hi,

I suspect there is something I'm doing wrong, but in the datasets all the `..._k0.tiff` images are black.
Is there something I'm supposed to do to them first so that I can see them?

Thanks.

**Comment by julimueller** [comment]
Yes, take a look into the code. Images are stored in 16 bit and first need
to be converted to 8 bit.

John Mathews <notifications@github.com> schrieb am Do., 21. Jan. 2021,
18:02:
