### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by timegate** [julimueller/dtld_parsing#11]
Currently, I cannot download from http://www.traffic-light-data.com/.
Can I download the dataset please?

**Comment by julimueller** [comment]
Hi @timegate, thanks for your hint. The domain is currently down. In the meantime you can use the direct URL: https://www.uni-ulm.de/en/in/driveu/projects/driveu-traffic-light-dataset/ to download the dataset after registration.

**Comment by julimueller** [comment]
Online again.

**Comment by boyang9602** [comment]
Hi,

I have registered but I did not receive the download link. Is there any issue with the website? Thank you.

Regards,
Bo

**Comment by julimueller** [comment]
Check your Spam folder

boyang9602 ***@***.***> schrieb am Do., 2. Nov. 2023, 17:19:

**Comment by boyang9602** [comment]
Thank you for your reply. I checked my spam and trash folders but I did not find it.

**Comment by julimueller** [comment]
Then let me clarify that tomorrow. Maybe give it a second try and let me
know if it doesn't work i'll check it our tomorrow

boyang9602 ***@***.***> schrieb am Do., 2. Nov. 2023, 19:58:

**Comment by julimueller** [comment]
I saw your registration. I quickly tested it as well. Surprisingly, it
doesnt work with my gmail. The mail does not even appear in the spam or
junk folder. When registering with my company mail it works. Any chance to
use a non-gmail account? Thx!

Am Do., 2. Nov. 2023 um 20:26 Uhr schrieb Julian Müller <
***@***.***>:

**Comment by boyang9602** [comment]
It works. Thank you very much!
