### ISSUE TITLE
Display/load image in natural colors

### ISSUE THREAD

**Issue by matpy1** [julimueller/dtld_parsing#12]
Hello,
I am trying to load the images from this dataset in natural colors. I use the following code:

img_file = str(image_path)
img = cv2.imread(img_file, cv2.IMREAD_UNCHANGED)
img = cv2.cvtColor(img, cv2.COLOR_BAYER_GB2BGR)
img = np.right_shift(img, 4)
img = img.astype(np.uint8)
plt.figure(figsize=(20,20))
plt.imshow(img)

The "image_path" variable contains the path to one image ending with "k0.tiff". Unfortunately, when I display the images there seems to be a different color setting, as you can see in the attached image (yellow colors are showed as bluish).

Thank you for any help!

![DriveUImg](https://user-images.githubusercontent.com/91553944/135657681-e37a826e-e7b8-4b90-8adb-c7ba238f4c10.png)

**Comment by julimueller** [comment]
Hi @matpy1, 

I think your problem is that you convert the image to bgr (standard for opencv) but you use matplotlib to display it (expects rgb). Either use cv2.imshow to display or convert it to rgb by using cv2.COLOR_BAYER_GB2RGB instead.

**Comment by matpy1** [comment]
Thank you! I didn't notice that I was using bgr instead of rgb, now it works fine. Thanks!
