### ISSUE TITLE
why don't all xx_k0.tiff show any image (all are black)

### ISSUE THREAD

**Issue by SeokLeeUS** [julimueller/dtld_parsing#2]
I downloaded Bochum data, but data with the label of xx_k0.tiff shows all black. 
![image](https://user-images.githubusercontent.com/44729645/58649181-6ffee280-82d9-11e9-9ffb-341a962f55b1.png)

**Comment by julimueller** [comment]
Please use our tools of the repository to view the images.  They are stored in 16bit and cannot be viewed by many standard image viewers.

**Comment by SeokLeeUS** [comment]
Thanks, it works:

![image](https://user-images.githubusercontent.com/44729645/58668823-28437f80-8308-11e9-9471-cd5130078075.png)

**Comment by omkale221** [comment]
@SeokLeeUS which tool did you use from the repo?
