### ISSUE TITLE
Are images pre-rectified?

### ISSUE THREAD

**Issue by atyshka** [julimueller/dtld_parsing#6]
Hi Julian, I'm working on a fork of this repo to convert the dataset to Tensorflow records and had a quick question regarding calibration. Are the RGB (non-stereo) images provided pre-rectified or do we need to do that manually using the intrinsics provided? I don't see much warping in the sample images but I want to make sure that Tensorflow is ingesting properly rectified data.

EDIT: Looking through the python code, it seems that the bounding box coordinates are rectified using opencv but the images themselves are not. Would I be correct in assuming that the bounding boxes are unrectified and the images themselves are rectified? That would be a little counter-intuitive.

**Comment by julimueller** [comment]
The images are not rectified. However as you have recognized the distortion
is not such a big issue here. If you want to rectify the images you have to
do it on your own, all necessary matrices are available in the dataset.

atyshka <notifications@github.com> schrieb am Fr., 6. Dez. 2019, 23:40:

**Comment by julimueller** [comment]
To your EDIT: Be careful, the bbox  coordinates themselves are not rectified. We offer one method which rectifies the coordinates so that these can be used together with the disparity image (which was calculated using left and right unrectified images).

**Comment by atyshka** [comment]
Yes that makes sense. Thanks for the clarification, closing for now. Hopefully will have a PR in a week or so.
