### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by poormag** [julimueller/dtld_parsing#8]
Hi, i got this problem during visualization of images. I did everything according to instructions:
 
`python3 load_dtld.py --label_file Berlin_all.yml --calib_dir /dtld_parsing-master/calibration --data_base_dir /Berlin/
`

For some time everything was going well, i think:

```
2020-04-23 14:15:12.976 INFO load_dtld - main: Intrinsic Matrix:

[[2290.51     0.    1066.94 ]
 [   0.    2290.51   477.152]
 [   0.       0.       1.   ]]

2020-04-23 14:15:12.977 INFO load_dtld - main: Extrinsic Matrix:

[[ 0.0037 -0.0453  0.999   2.105 ]
 [-0.9998  0.0188  0.0047  0.049 ]
 [-0.0189 -0.9988 -0.0452  0.919 ]]

2020-04-23 14:15:12.978 INFO load_dtld - main: Projection Matrix:

[[2269.699585    0.       1051.294655    0.      ]
 [   0.       2269.699585  458.462746    0.      ]
 [   0.          0.          1.          0.      ]]

2020-04-23 14:15:12.979 INFO load_dtld - main: Rectification Matrix:

[[ 0.999999 -0.001186  0.000677]
 [ 0.001181  0.999972  0.007356]
 [-0.000686 -0.007355  0.999973]]

2020-04-23 14:15:12.980 INFO load_dtld - main: Distortion Matrix:

[[-0.036004  0.        0.        0.        0.      ]]
```
But then i got this error:
```
Traceback (most recent call last):
  File "load_dtld.py", line 106, in <module>
    main(parse_args())
  File "load_dtld.py", line 76, in main
    img_disp = img.visualize_disparity_image()
  File "/traffic_lights/dtld_parsing-master/python/dtld_parsing/driveu_dataset.py", line 206, in visualize_disparity_image
    img = self.get_disparity_image()
  File "/traffic_lights/dtld_parsing-master/python/dtld_parsing/driveu_dataset.py", line 189, in get_disparity_image
    img[img == 65535] = 0
TypeError: 'NoneType' object does not support item assignment
```
Do you have any advises for me? Some image didn't find or..?

**Comment by julimueller** [comment]
Looks like the images are not correctly loaded because of an errorneous image path.

I think your argument --data_base_dir /Berlin/  is wrong. You should give the root directory where the data is stored, so if your Berlin folder is at /scratch/DTLD/Berlin.. you should call "--data_base_dir /scratch/DTLD/" because this is the entire dataset root dir.

Optional: Leave --data_base_dir empty and set all image paths in Berlin_all.yml to an absolute path, then it should also work.

**Comment by poormag** [comment]
> Looks like the images are not correctly loaded because of an errorneous image path.
> 
> I think your argument --data_base_dir /Berlin/ is wrong. You should give the root directory where the data is stored, so if your Berlin folder is at /scratch/DTLD/Berlin.. you should call "--data_base_dir /scratch/DTLD/" because this is the entire dataset root dir.
> 
> Optional: Leave --data_base_dir empty and set all image paths in Berlin_all.yml to an absolute path, then it should also work.

No, it's okay with path cuz, i have removed some ugly part of path for question. And as you can see some of images can be read, am I right?

**Comment by julimueller** [comment]
I cannot see that anything was loaded. What do you mean with "ugly part"? You have two options - either replace the paths by absolute paths or properly set the data_base_dir parameter.

**Comment by julimueller** [comment]
Please add


scale = 1.0 / 16.0
**print(self.disp_file_path)**
img = cv2.imread(self.disp_file_path, cv2.IMREAD_UNCHANGED)
img[img == 65535] = 0

execute python3 setup.py install again, run 

python3 load_dtld.py ... 

again and tell me the output of print(self.disp_file_path)

**Comment by poormag** [comment]
> I cannot see that anything was loaded. What do you mean with "ugly part"? You have two options - either replace the paths by absolute paths or properly set the data_base_dir parameter.

I mean my name, name of project, my granny's name and etc.I wrote a full path I mean like you said. 



> Please add
> 
> scale = 1.0 / 16.0
> **print(self.disp_file_path)**
> img = cv2.imread(self.disp_file_path, cv2.IMREAD_UNCHANGED)
> img[img == 65535] = 0
> 
> execute python3 setup.py install again, run
> 
> python3 load_dtld.py ...
> 
> again and tell me the output of print(self.disp_file_path)

OK

**Comment by poormag** [comment]
It prints this "`/Mary/traffic_lights/DTLD/Berlin//Berlin/Berlin1/2015-04-17_10-50-05/DE_BBBR667_2015-04-17_10-50-13-633939_nativeV2.tiff`"

**Comment by poormag** [comment]
I have also removed '+/' and got a normal path  without double slash  (`/Mary/traffic_lights/DTLD/Berlin/Berlin1/2015-04-17_10-50-05/DE_BBBR667_2015-04-17_10-50-13-633939_nativeV2.tiff`) but it doesnt help

**Comment by julimueller** [comment]
The double slash does not have any impact.

And this file really exists? What does "ls Mary/traffic_lights/DTLD/Berlin/Berlin1/2015-04-17_10-50-05/DE_BBBR667_2015-04-17_10-50-13-633939_nativeV2.tiff" in a terminal output?

**Comment by julimueller** [comment]
BTW: Your first answer has /Mary/traffic_lights/DTLD/Berlin//Berlin/Berlin1/2015-04-17_10-50-05/DE_BBBR667_2015-04-17_10-50-13-633939_nativeV2.tiff.

I said you should NOT use --data_base_dir Berlin. It will not work, as you can see Berlin is now appearing two times .

**Comment by poormag** [comment]
the problem is: i can take this path and put it in cv2, then got an array of pixels.
```
cv2.imread('/Mary/traffic_lights/DTLD/Berlin/Berlin1/2015-04-17_10-50-05/DE_BBBR667_2015-04-17_10-50-13-633939_nativeV2.tiff')
Out[6]: 
array([[[255, 255, 255],
        [112, 112, 112],
        [ 80,  80,  80],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[176, 176, 176],
        [176, 176, 176],
        [128, 128, 128],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[176, 176, 176],
        [176, 176, 176],
        [128, 128, 128],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[ 96,  96,  96],
        [ 96,  96,  96],
        [ 48,  48,  48],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[ 96,  96,  96],
        [ 96,  96,  96],
        [ 16,  16,  16],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [ 16,  16,  16],
        [ 16,  16,  16],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)
```

But when im  running script i have an error with this path and i have no idea why. 

```
2020-04-23 16:30:30.568 INFO load_dtld - main: Distortion Matrix:

[[-0.036004  0.        0.        0.        0.      ]]

/Mary/traffic_lights/DTLD/Berlin/Berlin1/2015-04-17_10-50-05/DE_BBBR667_2015-04-17_10-50-13-633939_nativeV2.tiff
Traceback (most recent call last):
  File "load_dtld.py", line 106, in <module>
    main(parse_args())
  File "load_dtld.py", line 76, in main
    img_disp = img.visualize_disparity_image()
  File "/Mary/traffic_lights/dtld_parsing-master/python/dtld_parsing/driveu_dataset.py", line 207, in visualize_disparity_image
    img = self.get_disparity_image()
  File "/Mary/traffic_lights/dtld_parsing-master/python/dtld_parsing/driveu_dataset.py", line 190, in get_disparity_image
    img[img == 65535] = 0
TypeError: 'NoneType' object does not support item assignment
```

Anyway, i will not disturb you anymore (i see you dont know) if I will find the mistake i will put an answer here.

**Comment by poormag** [comment]
I don’t know how it worked for you guys, but my version of cv2 does not allow reading tiff files in a stream.  As I thought there is no error in the path, using `skiimage.io.imread` instead of `cv2.imread` solved the problem of reading tiff files in the stream, but additional transformations are required to correctly display

**Comment by julimueller** [comment]
Glad to hear, however you are the first one reporting such an issue. I use cv imread for reading 16 bit tiffs for many years without any issues. Nobdy else reported that issue and we have a lof of active users of the dataset.

Have fun using the data!

**Comment by poormag** [comment]
This is no less strange for me, I just tried using other libraries like PIL and skimage and it worked, but there are similar problems with StackoverFlow.  So the first, but maybe not the last.  Thank you for your work.

**Comment by poormag** [comment]
Ok, i did a little research about this problem and figure out that I'm using cv2 openvino build and this one doesn't work with tiff-files, now I have changed the environment and everything is okay too.
